In [1]:
import torch

from diffdrr import DRR, load_example_ct

In [2]:
volume, spacing = load_example_ct()

params = torch.tensor([[250.0, 3.14, 0.0, 1.57, 150.0, 150.0, 150.0]])

drr = DRR(
    volume,
    spacing,
    height=100,
    delx=8.0,
    optimization_mode=True,
    params=params
).to(device="mps", dtype=torch.float16)

In [3]:
source, target = drr.detector.make_xrays(
    drr.sdr,
    drr.rotations,
    drr.translations,
)

In [4]:
drr()

/Users/vivek/Documents/MedicalVision/DiffDRR/diffdrr/projectors/siddon.py:52: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1670525498485/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  alphas[~good_idxs] = torch.nan


NotImplementedError: The operator 'aten::sort.values_stable' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

In [5]:
drr.to("cpu").to(torch.float64)

Parameter containing:
tensor([[250.]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[3.1406, 0.0000, 1.5703]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[150., 150., 150.]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.7031, 0.7031, 2.5000], dtype=torch.float64)
Parameter containing:
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ...

In [6]:
drr()

tensor([[[     0.0000,      0.0000,      0.0000,  ...,      0.0000,
               0.0000,      0.0000],
         [     0.0000,      0.0000,      0.0000,  ...,      0.0000,
               0.0000,      0.0000],
         [     0.0000,      0.0000,      0.0000,  ...,      0.0000,
               0.0000,      0.0000],
         ...,
         [     0.0000,      0.0000,      0.0000,  ..., 167733.9253,
          167572.3324, 170933.6458],
         [     0.0000,      0.0000,      0.0000,  ..., 170623.8087,
          169063.3625, 170242.3076],
         [     0.0000,      0.0000,      0.0000,  ..., 177162.3036,
          174305.1371, 171680.9659]]], dtype=torch.float64,
       grad_fn=<ViewBackward0>)

In [6]:
drr.siddon.spacing

Parameter containing:
tensor([0.7031, 0.7031, 2.5000], device='mps:0', dtype=torch.float16)

In [7]:
drr.siddon.volume.device

device(type='mps', index=0)

In [13]:
dummy = torch.tensor([[0.]]).to(device="mps", dtype=torch.float16)

In [34]:
test = torch.tensor([[1]])
test.dtype, test.device

(torch.int64, device(type='cpu'))

In [35]:
test.to(dummy)

tensor([[1.]], device='mps:0', dtype=torch.float16)

In [29]:
params = torch.tensor([250.0, 3.14, 0.0, 1.57, 150.0, 150.0, 150.0])
_ = drr(*params)

In [26]:
drr

Parameter containing:
tensor([250.])
Parameter containing:
tensor([[3.1400, 0.0000, 1.5700]], requires_grad=True)
Parameter containing:
tensor([[150., 150., 150.]], requires_grad=True)

In [53]:
_ = drr(*params)
print(_.device)

%timeit drr()

cpu
288 ms ± 32.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
drr.sdr.device

device(type='cpu')

In [50]:
drr.to("cpu")
%timeit drr()

263 ms ± 24.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
drr.to(device="mps", dtype=torch.float16)

Parameter containing:
tensor([250.], device='mps:0', dtype=torch.float16)
Parameter containing:
tensor([[3.1406, 0.0000, 1.5703]], device='mps:0', dtype=torch.float16,
       requires_grad=True)
Parameter containing:
tensor([[150., 150., 150.]], device='mps:0', dtype=torch.float16,
       requires_grad=True)

In [ ]:
drr.siddon

In [4]:
from diffdrr import Siddon

In [10]:
Siddon(volume, spacing)

RuntimeError: result type Float can't be cast to the desired output type Long

In [11]:
torch.tensor(volume.shape).dtype

torch.int64

In [14]:
t = torch.tensor(volume.shape)
t += 1

In [15]:
t

tensor([513, 513, 134])

In [7]:
volume

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.